core:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["packages/core/**"]

swc-plugin:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["packages/swc/**"]

webpack-plugin:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["packages/webpack-plugin/**"]

next-plugin:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["packages/next-plugin/**"]

vite-plugin:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["packages/vite-plugin/**"]

website:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["website/**"]

examples:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["examples/**"]
