on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
      paths_released: ${{ steps.release.outputs.paths_released }}
    steps:
      - id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
      - name: Debug outputs
        run: |
          echo "releases_created = ${{ steps.release.outputs.releases_created }}"
          echo "paths_released = ${{ steps.release.outputs.paths_released }}"

  publish:
    name: Publish
    if: needs.release-please.outputs.releases_created == 'true'
    needs: release-please
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ${{ fromJson(needs.release-please.outputs.paths_released) }}
    defaults:
      run:
        working-directory: ${{ matrix.package }}
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Build package
        run: bun run build
      - name: Publish package to npm
        run: |
          TARBALL=$(bun pm pack --quiet)
          npm publish "$TARBALL" --provenance
